const char *default_config =
"lservers = (\n"
"  { address = \"irc.stealth.net\"; chatnet = IRCNet; port = 6668; },\n"
"  { address = \"irc.efnet.net\"; chatnet = EFNet; port = 6667; },\n"
"  { address = \"irc.undernet.org\"; chatnet = Undernet; port = 6667; },\n"
"  { address = \"irc.dal.net\"; chatnet = DALnet; port = 6667; },\n"
"  { address = \"irc.openprojects.net\"; chatnet = OPN; port = 6667; },\n"
"  { address = \"irc.ptlink.net\"; chatnet = PTlink; port = 6667; }\n"
"  { address = \"silc.pspt.fi\"; chatnet = SILC; port = 706; }\n"
");\n"
"\n"
"chatnets = {\n"
"  IRCNet = { type = \"IRC\"; max_kicks = 4; max_modes = 3; max_msgs = 5; max_whois = 4; };\n"
"  EFNet = { type = \"IRC\"; max_kicks = 4; max_modes = 4; max_msgs = 3; };\n"
"  Undernet = { type = \"IRC\"; max_kicks = 4; max_modes = 3; max_msgs = 3; max_query_chans = \"1\"; };\n"
"  DALNet = { type = \"IRC\"; max_kicks = 4; max_modes = 6; max_msgs = 3; };\n"
"  OPN = { type = \"IRC\"; max_kicks = 1; max_modes = 6; max_msgs = 100; };\n"
"  PTLink = { type = \"IRC\"; max_kicks = 1; max_modes = 6; max_msgs = 100; };\n"
"  SILC = { type = \"SILC\"; };\n"
"};\n"
"\n"
"channels = (\n"
"  { name = \"#irssi\"; chatnet = ircnet; autojoin = No; },\n"
"  { name = \"#irssi\"; chatnet = opn; autojoin = No; },\n"
"  { name = \"#silc\"; chatnet = silc; autojoin = No; }\n"
");\n"
"\n"
"aliases = {\n"
"  J = \"join\";\n"
"  WJOIN = \"join -window\";\n"
"  WQUERY = \"query -window\";\n"
"  LEAVE = \"part\";\n"
"  BYE = \"quit\";\n"
"  EXIT = \"quit\";\n"
"  SIGNOFF = \"quit\";\n"
"  DESCRIBE = \"action\";\n"
"  DATE = \"time\";\n"
"  HOST = \"userhost\";\n"
"  LAST = \"lastlog\";\n"
"  SAY = \"msg *\";\n"
"  WI = \"whois\";\n"
"  WII = \"whois $0 $0\";\n"
"  WW = \"whowas\";\n"
"  W = \"who\";\n"
"  N = \"names\";\n"
"  M = \"msg\";\n"
"  T = \"topic\";\n"
"  C = \"clear\";\n"
"  CL = \"clear\";\n"
"  K = \"kick\";\n"
"  KB = \"kickban\";\n"
"  KN = \"knockout\";\n"
"  BANS = \"ban\";\n"
"  B = \"ban\";\n"
"  MUB = \"unban *\";\n"
"  UB = \"unban\";\n"
"  IG = \"ignore\";\n"
"  UNIG = \"unignore\";\n"
"  SB = \"scrollback\";\n"
"  UMODE = \"mode $N\";\n"
"  WC = \"window close\";\n"
"  WN = \"window new hide\";\n"
"  SV = \"say Irssi $J - http://irssi.org/\";\n"
"  GOTO = \"sb goto\";\n"
"  CHAT = \"dcc chat\";\n"
"};\n"
;
