#!/bin/sh

distribution=$1
dist_version=$2
package=$3
distdir=$4

if test -f $distdir.tar.gz; then
  sha512sum $distdir.tar.gz > $distdir.tar.gz.sum
fi
if test -f $distdir.tar.bz2; then
  sha512sum $distdir.tar.bz2 > $distdir.tar.bz2.sum
fi

