#!/bin/sh

distribution=$1
dist_version=$2
package=$3
distdir=$4
release=$5

if test -z $release; then
  release="0.fc7"
fi

sed -e "s/SILC_VERSION/$dist_version/" -e "s/SILC_RELEASE/$release/" \
  silc-toolkit.spec.in > silc-toolkit.spec

./configure

cd doc
make dist-hook
rm -rf toolkit
make toolkit-ref-html
cp ../lib/doc/*.gif toolkit
cd ..
