#!/bin/sh
#
# Author: Pekka Riikonen <priikone@silcnet.org>
#
# Copyright (C) GNU GPL 2001 Pekka Riikonen
#
# SILC Toolkit Reference Manual documentation script.  This will automatically
# generate documentation from the source tree.  This will require the 
# robodoc compiled in util/robodoc and php utility installed in your system.
#
# This will tarverse the given directory and all subdirectories for the
# SILC style header files.  All header files starting with prefix `silc' 
# will be checked.  For example, silcpkcs.h.
#
# Usage: ./sildoc <type> <source directory> <destination directory> <robodoc>
#
# The <source directory> is the directory where this starts checking for
# the headers and will traverse all subdirectories.  The <destination
# directory> is the directory to where the documentation is generated.
#

# Arguments checking
if [ $# -lt "4" ]; then
  echo "Usage: ./silcdoc <type> <source directory> <destination directory> <robodoc>"
  echo "Supported types: HTML"
#  echo "Supported types: HTML, ASCII, LATEX or RTF"
  exit 1
fi

TYPE=$1
SRC=$2
DST=$3
ROBO=$4

# Get all headers in the source directory
headers=`find $SRC -name "silc*.h"`

#
# ASCII documentation
#
#if [ "$TYPE" = "ASCII" ]; then
#
#fi

#
# HTML documentation
#
if [ "$TYPE" = "HTML" ]; then
  rm -rf /tmp/silcdoc.html
  rm -rf /tmp/silcdoc_html.html
  mkdir /tmp/silcdoc.html
  mkdir /tmp/silcdoc_html.html
  cp $headers /tmp/silcdoc.html

  # Generate index template from the DIRECTORY files
  files=`find $SRC -name "DIRECTORY"`
  for i in $files
  do
    # Get library name
    name=`grep "@LIBRARY=" $i |cut -d=  -f2`
    fname=`grep "@FILENAME=" $i |cut -d=  -f2`
    links=`grep "@LINK=" $i |cut -d=  -f2 |cut -d:  -f1`

    # Generate links to template file that can be included into various
    # places on the webpage.
    echo "<A HREF="$fname"><IMG SRC="box.gif" border="0" alt="">$name</A><BR>" >>$DST/index.tmpl
    for k in $links
    do
      n=`grep $k $i |cut -d=  -f2 |cut -d:  -f2`
      echo "<LI><A HREF="$k">$n</A>" >>$DST/$fname.links
      echo "&nbsp;&nbsp;&nbsp; <A HREF="$k"><IMG SRC="box2.gif" border="0" alt="">$n</A><BR>" >>$DST/index.tmpl
    done
  done

  # Copy all HTML files to destination
  htmlfiles=`find $SRC -name "silc*.html"`
  for i in $htmlfiles
  do
    cp $i /tmp/silcdoc_html.html
  done
  path=`pwd`
  cd /tmp/silcdoc_html.html
  htmlfiles=`find . -name "silc*.html" | cut -d/  -f2`
  cd $path
  for i in $htmlfiles
  do
    # Generate the details and the layout
    f="/tmp/silcdoc_html.html/$i"
    sh gen.sh $DST gen_html_index.php $f $f
    cp /tmp/silcdoc_html.html/$i $DST
echo $f
  done

  # Generate the actual detailed documentation
  path=`pwd`
  cd /tmp/silcdoc.html
  headers=`find . -name "silc*.h" |cut -d/  -f2 |cut -d.  -f1`
  cd $path
  for i in $headers
  do
    $ROBO /tmp/silcdoc.html/$i.h $DST/$i.html $TYPE

    # Generate the TOC file
    sh gen.sh $DST gen_toc.php $DST/$i.html $DST/$i.html
    sh gen.sh $DST gen_html_index.php $DST/$i.html $DST/$i.html

    # Generate the details and the layout
    files=`find $DST -name ""$i"__*.html"`
    for k in $files
    do
      sh gen.sh $DST gen_index.php $k $k
    done

    rm -f $DST/$i__index.tmpl
  done

  # Generate the index and TOC files from the DIRECTORY files
  files=`find $SRC -name "DIRECTORY"`
  for i in $files
  do
    # Get library name
    name=`grep "@LIBRARY=" $i |cut -d=  -f2`
    fname=`grep "@FILENAME=" $i |cut -d=  -f2`

    # Generate links for this library
    sed -e "/@LINKS@/ r $DST/$fname.links" -e s/@LINKS@//g $i >$DST/$fname

    # Generate the TOC file for the library
    sh gen.sh $DST gen_toc.php $DST/$fname $DST/$fname
    sh gen.sh $DST gen_html_index.php $DST/$fname $DST/$fname

    # Generate the link for the top index.html for this library
    echo "<LI><A HREF="$fname">$name</A>" >>$DST/index.html.tmp
    rm -f $DST/$fname.links
  done

  # Generate the top index.html file
  index=`find $SRC -name "LIBINDEX"`
  version=`grep SILC_VERSION_STRING $SRC/../includes/version_internal.h |cut -d\"  -f2`
  curdate=`date`
  sed -e "/@VERSION@/s//$version/" -e "/@DATE@/s//$curdate/" -e "/@BODY@/ r $DST/index.html.tmp" -e s/@BODY@//g $index >$DST/index.html
  sh gen.sh $DST gen_toc.php $DST/index.html $DST/index.html
  sh gen.sh $DST gen_html_index.php $DST/index.html $DST/index.html

  rm -rf $DST/index.html.tmp
  rm -rf /tmp/silcdoc.html
  rm -rf /tmp/silcdoc_html.html
fi
