/* this file is automatically generated by configure - don't change */
void silc_core_init(void); void silc_core_deinit(void);
void silc_init(void) { silc_core_init();  }
void silc_deinit(void) {  silc_core_deinit(); }
