/*
  Automatically generated by Autodist 1.3.  Do not edit.

  Generated: Fri Dec 22 21:56:55 EET 2006 by priikone
  Distribution: default
  License:
*/

#ifndef _SILC_DISTDEFS_H
#define _SILC_DISTDEFS_H

#define SILC_DIST_TOOLKIT 1
#define SILC_DIST_ASN1 1
#define SILC_DIST_COMPILER 1
#define SILC_DIST_DOC 1
#define SILC_DIST_IDCACHE 1
#define SILC_DIST_INCLUDES 1
#define SILC_DIST_LIB 1
#define SILC_DIST_MATH 1
#define SILC_DIST_SILC 1
#define SILC_DIST_SKR 1
#define SILC_DIST_TMA 1
#define SILC_DIST_VCARD 1

#endif /* _SILC_DISTDEFS_H */
